name: flutter_credit_card
description: A Credit Card widget package, support entering card details, card flip animation.
version: 3.0.6
homepage: https://github.com/simformsolutions/flutter_credit_card
issue_tracker: https://github.com/simformsolutions/flutter_credit_card/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: 0.5.0
  camera: 0.10.3+2
  image: 4.0.15
  path_provider: 2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
  plugin:
    platforms:
      android:
        package: com.simform.flutter_credit_card
        pluginClass: FlutterCreditCardPlugin
      ios:
        pluginClass: FlutterCreditCardPlugin