name: flutter_credit_card
description: A Credit Card widget package, support entering card details, card flip animation.
version: 3.0.7
homepage: https://github.com/simformsolutions/flutter_credit_card
issue_tracker: https://github.com/simformsolutions/flutter_credit_card/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.simform.flutter_credit_card
        pluginClass: FlutterCreditCardPlugin
      ios:
        pluginClass: FlutterCreditCardPlugin
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
